importing the packages

In [203]:
import numpy as np
import os
os.chdir('C:/Users/Muskan/Downloads/Loan Dataset')

In [204]:
#to remove scientif notation from numbers, fit characters in single line to 100 and decimal points to 2
np.set_printoptions(suppress=True,linewidth=100,precision=2)

importing the data

In [205]:
#Load data from a text file, with missing values handled as specified
raw_data_np=np.genfromtxt("loan-data.csv",delimiter=';',skip_header=1,autostrip=True)
raw_data_np

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

Checking for incomplete data

In [206]:
#missing values
np.isnan(raw_data_np).sum()

88005

In [207]:
#fillinf data in place of missing values 
temp_fill=np.nanmax(raw_data_np)+1
#Return the maximum of an array or maximum along an axis, ignoring any NaNs. 
#fill missing values with a value greater than every other in the dataset
temp_mean=np.nanmean(raw_data_np,axis=0)
#contains the mean values on every column 

<ipython-input-207-2bca7034ff4b>:5: RuntimeWarning: Mean of empty slice
  temp_mean=np.nanmean(raw_data_np,axis=0)


In [208]:
#np.nan will show values that are not number so the column means with nans could be strings
temp_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [209]:
#it is better to have two seperate arrays of numeric and non-numeric data
temp_stats=np.array([np.nanmin(raw_data_np,axis=0),
                    temp_mean,
                    np.nanmax(raw_data_np,axis=0)])
#the resultant array will have min value of each column, mean and max stacked over each other

<ipython-input-209-219b166dc439>:2: RuntimeWarning: All-NaN slice encountered
  temp_stats=np.array([np.nanmin(raw_data_np,axis=0),
<ipython-input-209-219b166dc439>:4: RuntimeWarning: All-NaN slice encountered
  np.nanmax(raw_data_np,axis=0)])


In [210]:
temp_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

Splitting Data in numeric and string

In [211]:
#array of column numbers which have strings
columns_strings=np.argwhere(np.isnan(temp_mean)).squeeze()
#np.argwhere=Find the indices of array elements that are non-zero, grouped by element.
columns_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [212]:
#array of column numbers which have numerical data
columns_numeric=np.argwhere(np.isnan(temp_mean)==False).squeeze()
columns_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

Re-importing the dataset

In [213]:
#loading the string dataset
loan_data_strings=np.genfromtxt("loan-data.csv",
                                delimiter=';',
                                skip_header=1,
                                autostrip=True,
                                usecols=columns_strings,
                                dtype=np.str)
#autostrip= Whether to automatically strip white spaces from the variables
#usecols=Which columns to read, with 0 being the first. 
loan_data_strings

<ipython-input-213-68f06f396d2c>:7: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.str)


array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [214]:
#loading the numeric dataset
loan_data_numeric=np.genfromtxt("loan-data.csv",
                                delimiter=';',
                                skip_header=1,
                                autostrip=True,
                                usecols=columns_numeric,
                                filling_values=temp_fill)


Putting Headers (Names of columns) into string and numeric data

In [215]:
#string columns header
header_full=np.genfromtxt("loan-data.csv",
                                delimiter=';',
                                autostrip=True,
                                skip_footer=raw_data_np.shape[0],
                                dtype=np.str)
header_full
#skip_footer here removes all the rows after the header to give only the column names from
#the dataset
#dtype is str as names of columns are string values

<ipython-input-215-3cb8eb8f1855>:6: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.str)


array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [216]:
#assigning column names to respective string and numeric indices created earlier
header_strings,header_numeric= header_full[columns_strings],header_full[columns_numeric]#

In [217]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [218]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

Creating Checkpoints

In [219]:
'''
checkpoints are a copy of our dataset or parts of it, so we don't lose progress if 
we accidentally over write variable names 
important when we need to clean or pre-process many parts of data
'''
def checkpoint(file_name,checkpoint_header,checkpoint_data):
    np.savez(file_name,header=checkpoint_header,data=checkpoint_data)
    checkpoint_variable=np.load(file_name+".npz")
    return(checkpoint_variable)
#np.savez=save several arrays into a single file in uncompressed .npz format.

In [220]:
checkpoint_test=checkpoint("checkpoint-test",header_strings,loan_data_strings)

In [221]:
#checking the function for correctly storing string dataset we created
checkpoint_test['header']

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [222]:
checkpoint_test['data']

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [223]:
#once again confirming if the checkpoint stores the correct data
np.array_equal(checkpoint_test['data'],loan_data_strings)

True

## Manipulating String Columns

In [224]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

#### Issue Date column

In [225]:
#making column names more descriptive for example first column is the loan issue date
header_strings[0]="issue_date"

In [226]:
loan_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [227]:
#looking from the dataset, issue date is first 3 letters of the month followed by year
np.unique(loan_data_strings[:,0])
#extracting the unique column values of the issue_date column to verify the pattern
#all loans are issues in 2015 from the result shown below

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [228]:
#since all loans are issues in 2015 we can remove the '-15' from the data 
np.chararray.strip(loan_data_strings[:,0],"-15")
#np.chararray.strip= For each element in self, return a copy with the leading and trailing characters removed.

chararray(['May', '', 'Sep', ..., 'Jun', 'Apr', 'Dec'], dtype='<U69')

In [229]:
#overwriting the column values without '-15'
loan_data_strings[:,0]=np.chararray.strip(loan_data_strings[:,0],"-15")

In [230]:
np.unique(loan_data_strings[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [231]:
#during analysis month values are better represented as integers as they occupy less space
months=np.array(['','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'])
#the empty string in the beginning of array is present in the column issue_date also

In [232]:
# will assign 0 to missing values, candidates with no issue_Date
# will assign numbers 1-12 to January to December
for i in range(13):
    loan_data_strings[:,0]=np.where(loan_data_strings[:,0]==months[i],
                                    i,
                                    loan_data_strings[:,0])
#numpy.where(condition[, x, y])=Return elements chosen from x or y depending on condition.

In [233]:
np.unique(loan_data_strings[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

#### Loan Status column

In [234]:
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [235]:
loan_data_strings[:,1]

array(['Current', 'Current', 'Current', ..., 'Current', 'Current', 'Current'], dtype='<U69')

In [236]:
np.unique(loan_data_strings[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [237]:
#checking the number of unique values to assign numbers to
np.unique(loan_data_strings[:,1]).size

9

In [238]:
'''
regression analysis would only care if the candidate is in a stable financial position.
Therefore it would be wrong to give 9 different integers to each unique value in status column
'': indicates mising value thus treatead as BAD or 0

'Charged Off': Referes to bad debt hence treated as 0
'Current':     Loan repayments are still active thus treated as GOOD or 1
'Default':     Defaulted loan treated as 0
'Fully Paid':  Loan is fully paid off treated as 1
'In Grace 
Period'     :  borrower does not have to pay the issuer any monies toward the loan, 1
'Issued'    :  Loan must have been issued to someone who is capable of paying off, 1
'Late(16-30 
days)'      :  usually repayment might be late due to salary being late, so given 1
'Late(31-120
days)'      : long delay in repayment, might default so given 1

0='bad',1='good' in terms of repayment classification
'''

"\nregression analysis would only care if the candidate is in a stable financial position.\nTherefore it would be wrong to give 9 different integers to each unique value in status column\n'': indicates mising value thus treatead as BAD or 0\n\n'Charged Off': Referes to bad debt hence treated as 0\n'Current':     Loan repayments are still active thus treated as GOOD or 1\n'Default':     Defaulted loan treated as 0\n'Fully Paid':  Loan is fully paid off treated as 1\n'In Grace \nPeriod'     :  borrower does not have to pay the issuer any monies toward the loan, 1\n'Issued'    :  Loan must have been issued to someone who is capable of paying off, 1\n'Late(16-30 \ndays)'      :  usually repayment might be late due to salary being late, so given 1\n'Late(31-120\ndays)'      : long delay in repayment, might default so given 1\n\n0='bad',1='good' in terms of repayment classification\n"

In [239]:
status_bad=np.array(['','Charged Off','Default','Late (31-120 days)'])

In [240]:
#aaplying an if condtion using np.where to assign 0 to values in bad_status array and 1 to the rest
loan_data_strings[:,1]=np.where(np.isin(loan_data_strings[:,1],status_bad),0,1)

In [241]:
#confirming if the np.where function worked correctly
np.unique(loan_data_strings[:,1])

array(['0', '1'], dtype='<U69')

#### Term column

In [242]:
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [243]:
np.unique(loan_data_strings[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [244]:
#looking at the data values in the column, all values are in months. hence we can remove months
loan_data_strings[:,2]=np.chararray.strip(loan_data_strings[:,2]," months")
loan_data_strings[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [245]:
#renaming the column to clarify what it contains
header_strings[2]='term_months'

In [246]:
'''
in Credit Risk Modelling, any missing value is the worst case scenario for repaybility
also if the loan term is 60 months=5 years then that is the worst case scenario here
as it is difficult to repay a loan stretched over 5 years for this case. 
thus we will subsitute the white space here as 60 months
'''

'\nin Credit Risk Modelling, any missing value is the worst case scenario for repaybility\nalso if the loan term is 60 months=5 years then that is the worst case scenario here\nas it is difficult to repay a loan stretched over 5 years for this case. \nthus we will subsitute the white space here as 60 months\n'

In [247]:
loan_data_strings[:,2]=np.where(loan_data_strings[:,2]=='',60,loan_data_strings[:,2])

In [248]:
np.unique(loan_data_strings[:,2])

array(['36', '60'], dtype='<U69')

#### Grade and Subgrade columns

In [249]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [250]:
#checking unique values in grade column
np.unique(loan_data_strings[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [251]:
#checking unique values in subgrade column
np.unique(loan_data_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [252]:
#filling missing values in sub-grade as the grade column and sub-grade column convey the same info
for i in np.unique(loan_data_strings[:,3])[1:]: #starting from the non missing value thats why starting from 1:
    loan_data_strings[:,4]=np.where((loan_data_strings[:,4]=='') & (loan_data_strings[:,3]==i),
    i+'5',
    loan_data_strings[:,4])

'''
this function works by replacing the value in sub-grade column by example checking if the 
corresponsing grade column value is 'A' then assign the value of 'A5' to the missing value
in sub grade value. This is because 'A5' is the lowest quality in the 'A' category and any
missing data should be assumed the worst case in that category
'''

"\nthis function works by replacing the value in sub-grade column by example checking if the \ncorresponsing grade column value is 'A' then assign the value of 'A5' to the missing value\nin sub grade value. This is because 'A5' is the lowest quality in the 'A' category and any\nmissing data should be assumed the worst case in that category\n"

In [253]:
np.unique(loan_data_strings[:,4],return_counts=True)
#return counts gives the freuquency disti of all the unique vales
#there are 9 empty rows still, which means neither a grade nor a sub-grade was present

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5],
       dtype=int64))

#### Introducing category H1 in sub-grade for rest of the missing values

In [254]:
#since missing values should be the worst-case we can replace the 9 missing values with the next category,H1
loan_data_strings[:,4]=np.where(loan_data_strings[:,4]=='',
                               'H1',
                               loan_data_strings[:,4])

In [255]:
np.unique(loan_data_strings[:,4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

#### Removing Grade

In [256]:
#the grade column is redundant after getting same info from the sub grade column
loan_data_strings=np.delete(loan_data_strings,3,axis=1)
#removes column index 3 = Grade from axis = 1 which states column axis

In [257]:
#checking which is the new column index 3
loan_data_strings[:,3]
#column index 3 is now the sub-grade column

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [258]:
#removing grade column header 
header_strings=np.delete(header_strings,3)
header_strings[3]
#header_string index 3 is now sub-grade

'sub_grade'

#### Converting Sub-Grade column values to numbers

In [259]:
np.unique(loan_data_strings[:,3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [260]:
# to avoid using np.where for so many values, create a dictionary for values in sub-grade column
#since the grading of loans reflects quality form best to worst in A1 to H1 we will designative numbers starting grom 1 to A1
keys=list(np.unique(loan_data_strings[:,3]))
values=list(range(1,np.unique(loan_data_strings[:,3]).shape[0]+1))
dict_sub_grade=dict(zip(keys,values))

In [261]:
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [262]:
#converting each value from the subgrade to a numerical value extracted from keys
for i in np.unique(loan_data_strings[:,3]):
    loan_data_strings[:,3]=np.where(loan_data_strings[:,3]==i,
                                   dict_sub_grade[i],
                                   loan_data_strings[:,3])

In [263]:
#resultant array
np.unique(loan_data_strings[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

#### Verification Status Column

In [264]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [265]:
np.unique(loan_data_strings[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [266]:
'''
Any missing value in a loan would be considered a non-verified loan. We can assign a value of
0 to the missing and 'Not Verirfed' values. 
Meanwhile 'Source Verified' indicates that investor backing is proved.Hence we can assign value
of 1 to both the 'Verified' and 'Source Verified' columns
'''

"\nAny missing value in a loan would be considered a non-verified loan. We can assign a value of\n0 to the missing and 'Not Verirfed' values. \nMeanwhile 'Source Verified' indicates that investor backing is proved.Hence we can assign value\nof 1 to both the 'Verified' and 'Source Verified' columns\n"

In [267]:
loan_data_strings[:,4]=np.where((loan_data_strings[:,4]=='') | (loan_data_strings[:,4]=='Not Verified'),
                                0,
                                1)                   

In [268]:
np.unique(loan_data_strings[:,4])

array(['0', '1'], dtype='<U69')

#### URL column

In [269]:
loan_data_strings[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [270]:
#the url value until the ID numbers is the same and can be discarded
loan_data_strings[:,5]=np.chararray.strip(loan_data_strings[:,5],'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

In [271]:
loan_data_strings[:,5]

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [272]:
#these are numbers stored as string values
#while loading the dataset there was already an ID column present as the first column
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [273]:
#the 'id' column and the new 'url' column look the same
print(loan_data_numeric[:,0].astype(dtype=np.int32))
print(loan_data_strings[:,5].astype(dtype=np.int32))

[48010226 57693261 59432726 ... 50415990 46154151 66055249]
[48010226 57693261 59432726 ... 50415990 46154151 66055249]


In [274]:
#although both columns look the same in numeric form, we can confirm their equality
np.array_equal(loan_data_numeric[:,0].astype(dtype=np.int32),loan_data_strings[:,5].astype(dtype=np.int32))

True

In [275]:
#since both columns represnt same info, we can remove URL column
loan_data_strings=np.delete(loan_data_strings,5,axis=1)
header_strings=np.delete(header_strings,5)

In [276]:
loan_data_strings[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [277]:
#addr_state is now column index5
header_strings[5]

'addr_state'

#### State Address

In [278]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [279]:
#creating a clear column name
header_strings[5]="state_address"

In [280]:
np.unique(loan_data_strings[:,5],return_counts=True)

(array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
        'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
        'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
        'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69'),
 array([ 500,   26,  119,   74,  220, 1336,  201,  143,   27,   27,  690,  321,   44,  389,  152,
          84,   84,  116,  210,  222,   10,  267,  156,  160,   61,   28,  261,   16,   25,   58,
         341,   57,  130,  777,  312,   83,  108,  320,   40,  107,   24,  143,  758,   74,  242,
          17,  216,  148,   49,   27], dtype=int64))

In [281]:
#checking no of states including the blank space or missing values
np.unique(loan_data_strings[:,5]).size
#on a closer look, the missing state is Iowa, which could have been taken as a benchmark state 
#to base other state values on

50

In [282]:
states_names,states_count=np.unique(loan_data_strings[:,5],return_counts=True)

In [283]:
#we can sort the freuency distribution of states in descending order
states_count_sorted=np.argsort(-states_count)
states_names[states_count_sorted],states_count[states_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10], dtype=int64))

In [284]:
'''
there are 500 missing values in the column as shown above. We will have to get rid of missing
values. To do this, we can divide all the states in 4 major regions. By doing this we avoid
each individual state data getting affected by outliers as there is too little data for each 
state to be examined individually. Thus we can assign the value 0 to missing data in the column,
as it won't correspond to any region's data. 
'''

"\nthere are 500 missing values in the column as shown above. We will have to get rid of missing\nvalues. To do this, we can divide all the states in 4 major regions. By doing this we avoid\neach individual state data getting affected by outliers as there is too little data for each \nstate to be examined individually. Thus we can assign the value 0 to missing data in the column,\nas it won't correspond to any region's data. \n"

In [285]:
#assigning 0 to missing values
loan_data_strings[:,5]=np.where(loan_data_strings[:,5]=='',
                                0,
                                loan_data_strings[:,5])

#### Creating 4 regions for state categories

In [286]:
#source for region segregation:https://www2.census.gov/geo/pdfs/reference/Geography_Notes.pdf
states_west=np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south=np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest=np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east=np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

In [287]:
# Assigning numbers 1-4 to regions and 0 to missing values
loan_data_strings[:,5]=np.where(np.isin(loan_data_strings[:,5],states_west),1,loan_data_strings[:,5])
loan_data_strings[:,5]=np.where(np.isin(loan_data_strings[:,5],states_south),2,loan_data_strings[:,5])
loan_data_strings[:,5]=np.where(np.isin(loan_data_strings[:,5],states_midwest),3,loan_data_strings[:,5])
loan_data_strings[:,5]=np.where(np.isin(loan_data_strings[:,5],states_east),4,loan_data_strings[:,5])

In [288]:
#checking the assignment is correct or not
np.unique(loan_data_strings[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

#### Converting strings to numerical format

In [289]:
#after assigning values to strings, these values are still strings
loan_data_strings

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [290]:
#these strings can be converted to numeric data type
loan_data_strings=loan_data_strings.astype(np.int)
loan_data_strings

<ipython-input-290-7547426f7875>:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  loan_data_strings=loan_data_strings.astype(np.int)


array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

#### Checkpoint #1:Strings 

In [291]:
checkpoint_strings=checkpoint("Checkpoint-Strings",header_strings,loan_data_strings)

In [292]:
checkpoint_strings['header']

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [293]:
checkpoint_strings['data']

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [294]:
np.array_equal(checkpoint_strings['data'],loan_data_strings)

True

## Manipulating Numeric Columns

In [295]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [296]:
#checking for missing values
np.isnan(loan_data_numeric).sum()
#the dataset shows no nan values

0

Replacing temp_fill values

In [ ]:
#we filled the nan values with temp_fill earlier
#we have to replace missing data with worst case scenario according to Credit Risk Modelling

In [297]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

#### ID column

In [298]:
#checking if there is any temp_fill value in the ID column
np.isin(loan_data_numeric[:,0],temp_fill)

array([False, False, False, ..., False, False, False])

In [299]:
np.isin(loan_data_numeric[:,0],temp_fill).sum()
#thus since there are no temp_fill values in the ID column, there were no missing values

0

#### Other columns

In [300]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [ ]:
'''
the rest of the columns from loan_amt to total_pyment, the only column for which it would be 
bad to have the lowest possible value is 'funded_amt'. Thus we will fill the missing values in
this column with the min of all values in the column.
For all other columns, the highest or the max values would be bad for repayability thus we will
fill missing values in these columns with column max
'''

#### Using the temp_stats created before to fill nan values

In [302]:
#the first row in temp_stats contains all columns' min, 2nd row mean, 3rd row max 
temp_stats[:,columns_numeric]
# ex total_amt column min value is 0 and max is 41913.62

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

#### Funded Amount Column

In [304]:
#funded amount missing values will be filled with the minimum amount
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [305]:
loan_data_numeric[:,2]=np.where(loan_data_numeric[:,2]==temp_fill,
                               temp_stats[0,columns_numeric[2]],
                               loan_data_numeric[:,2])
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

#### Loaned Amount,Interest Rate,Total Payment,Installment

In [306]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [307]:
#since we want max values in place of temp_fill in all these columns, can use a for loop
for i in [1,3,4,5]:
    loan_data_numeric[:,i]=np.where(loan_data_numeric[:,i]==temp_fill,
                                   temp_stats[0,columns_numeric[i]],
                                   loan_data_numeric[:,i])

In [308]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,        6.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,        6.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,        6.  ,       31.42,     2185.64],
       [46154151.  ,     1000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,        6.  ,      309.97,      301.9 ]])

#### Currency Exchange: Converting Dollars to Euros

In [311]:
import os
os.chdir("C:/Users/Muskan/Downloads/EUR-USD Exchange Rate 2015")
EUR_USD=np.genfromtxt("EUR-USD.csv",delimiter=',',autostrip=True)
EUR_USD
#the EUR-USD csv file contains monthly exchange rates 

array([[ nan,  nan,  nan,  nan,  nan],
       [1.21, 1.21, 1.11, 1.13, 0.  ],
       [1.13, 1.15, 1.12, 1.12, 0.  ],
       [1.12, 1.12, 1.05, 1.08, 0.  ],
       [1.07, 1.12, 1.05, 1.11, 0.  ],
       [1.12, 1.15, 1.08, 1.1 , 0.  ],
       [1.1 , 1.14, 1.09, 1.12, 0.  ],
       [1.11, 1.12, 1.08, 1.09, 0.  ],
       [1.1 , 1.17, 1.09, 1.13, 0.  ],
       [1.12, 1.15, 1.11, 1.13, 0.  ],
       [1.12, 1.15, 1.09, 1.1 , 0.  ],
       [1.1 , 1.11, 1.06, 1.06, 0.  ],
       [1.06, 1.11, 1.05, 1.09, 0.  ]])

In [323]:
#the first row contains nans so toview column names, change dtype to string
EUR_USD=np.genfromtxt("EUR-USD.csv",delimiter=',',autostrip=True)
EUR_USD

array([[ nan,  nan,  nan,  nan,  nan],
       [1.21, 1.21, 1.11, 1.13, 0.  ],
       [1.13, 1.15, 1.12, 1.12, 0.  ],
       [1.12, 1.12, 1.05, 1.08, 0.  ],
       [1.07, 1.12, 1.05, 1.11, 0.  ],
       [1.12, 1.15, 1.08, 1.1 , 0.  ],
       [1.1 , 1.14, 1.09, 1.12, 0.  ],
       [1.11, 1.12, 1.08, 1.09, 0.  ],
       [1.1 , 1.17, 1.09, 1.13, 0.  ],
       [1.12, 1.15, 1.11, 1.13, 0.  ],
       [1.12, 1.15, 1.09, 1.1 , 0.  ],
       [1.1 , 1.11, 1.06, 1.06, 0.  ],
       [1.06, 1.11, 1.05, 1.09, 0.  ]])

In [326]:
#only the 4th column, 'close' is useful as it reflects the adjusted closing exchange rate for each month
#importing just the 4th column(index no 3), close
EUR_USD=np.genfromtxt("EUR-USD.csv",delimiter=',',autostrip=True,skip_header=1,usecols=3)
EUR_USD

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [327]:
# the issue date column we created contains 0 for missing values and 1-12 intergers for months 
loan_data_strings[:,0]

array([ 5,  0,  9, ...,  6,  4, 12])

In [328]:
exchange_rate=loan_data_strings[:,0]
'''
To convert each $ value in loan_data_string to € value, we can assign all values of ex January
in EUR_USD to 1(coded for january) in exchange_rate array 
the EUR_USD array has index 0 for January so use i-1
'''
for i in range(1,13):
    exchange_rate=np.where(exchange_rate==i,
                          EUR_USD[i-1],
                          exchange_rate)

#the missing values can be replaced by the mean of all values in EUR_USD 

exchange_rate=np.where(exchange_rate==0,
                      np.mean(EUR_USD),
                      exchange_rate)
exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [329]:
exchange_rate.shape

(10000,)

In [330]:
loan_data_numeric.shape

(10000, 6)

In [331]:
#the exchange_rate array is one-dimensional whereas loan_data_numeric is 2D
#we need to reshape exchange_rate array to 2D
exchange_rate=np.reshape(exchange_rate,(10000,1))

In [333]:
#now that exchange_rate is 2D we can add it as a column in loan_data_numeric by using np.hstack
loan_data_numeric=np.hstack((loan_data_numeric,exchange_rate))
#the exchange_rate column would be added as the last column

In [336]:
#adding the column to header_numeric as an array as header_numeric is an array
header_numeric=np.concatenate((header_numeric,np.array(['exchange_rate_$_€'])))
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt',
       'exchange_rate_$_€'], dtype='<U19')

#### USD TO EUR

In [337]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt',
       'exchange_rate_$_€'], dtype='<U19')

In [338]:
#the ID and interest rate columns do not need to be converted only the following
columns_dollar=np.array([1,2,4,5])

In [340]:
#subsetting the exchange_rate column
loan_data_numeric[:,6]

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [343]:
for i in columns_dollar:
    loan_data_numeric=np.hstack((loan_data_numeric,
                        np.reshape(loan_data_numeric[:,i]/loan_data_numeric[:,6],(10000,1))))

                                #reshaping the exchange rate columns as they have to be array values
#to convert from usd to eur we have to divide column values by the exchange rate column 
#values which column index 6

In [344]:
# 4 more columns were added to loan_data_numeric, containing the euro values to their $ counterpart
loan_data_numeric.shape

(10000, 11)

#### Adding the new column names to header_numeric

In [345]:
#creating an array of new column headers
header_additional=np.array([column_name+'_EUR' for column_name in header_numeric[columns_dollar]])

In [346]:
header_numeric=np.concatenate((header_numeric,header_additional))

In [347]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt',
       'exchange_rate_$_€', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR',
       'total_pymnt_EUR'], dtype='<U19')

In [348]:
#indicating USD columns clearly
header_numeric[columns_dollar]=np.array([column_name+'_USD' for column_name in header_numeric[columns_dollar]])

In [349]:
header_numeric

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate_$_€', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR',
       'total_pymnt_EUR'], dtype='<U19')

In [350]:
#we can re_arrange USD and Eur columns to be next to each other
#we can create a list of column indices that need to be next to each other
columns_index_order=[0,1,7,2,8,3,4,9,5,10,6]

In [351]:
#the desired order
header_numeric[columns_index_order]

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR',
       'exchange_rate_$_€'], dtype='<U19')

In [352]:
header_numeric=header_numeric[columns_index_order]

In [353]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,       28.  ,     1947.47],
       [46154151.  ,     1000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

In [354]:
#we need to arrange the loan_data_numeric values in the same order
loan_data_numeric=loan_data_numeric[:,columns_index_order]

#### Interest Rate Column

In [355]:
header_numeric

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR',
       'exchange_rate_$_€'], dtype='<U19')

In [356]:
loan_data_numeric[:,5]

array([13.33,  6.  ,  6.  , ...,  6.  , 16.55,  6.  ])

In [357]:
#the conventional values of interest rates are b/w 0 to 1. so lets divide each value by 100
loan_data_numeric[:,5]=loan_data_numeric[:,5]/100

In [358]:
loan_data_numeric[:,5]

array([0.13, 0.06, 0.06, ..., 0.06, 0.17, 0.06])

#### Checkpoint #2: Numeric

In [359]:
checkpoint_numeric=checkpoint("Checkpoint-Numeric",header_numeric,loan_data_numeric)

In [361]:
checkpoint_numeric['header'],checkpoint_numeric['data']

(array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
        'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR',
        'exchange_rate_$_€'], dtype='<U19'),
 array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
        [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
        [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
        ...,
        [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
        [46154151.  ,     1000.  ,      899.74, ...,     3199.4 ,     2878.63,        1.11],
        [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]]))

## Creating the complete Dataset with both String and Numeric Arrays

In [362]:
#cross checking if the dimesions of the string and numeric arrays to stack them together
checkpoint_strings['data'].shape

(10000, 6)

In [363]:
checkpoint_numeric['data'].shape

(10000, 11)

In [365]:
#both the arrays have same no of rows so we can stack them side by side
#will keep numeric array on the left as it has IDs of loans
loan_data=np.hstack((checkpoint_numeric['data'],checkpoint_strings['data']))

In [366]:
loan_data

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,     1000.  ,      899.74, ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        0.  ,        3.  ]])

In [367]:
#checking if the dataset has any null values
np.isnan(loan_data).sum()

0

In [368]:
#getting all the column headers together
header_full=np.concatenate((checkpoint_numeric['header'],checkpoint_strings['header']))

In [369]:
header_full

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR',
       'exchange_rate_$_€', 'issue_date', 'loan_status', 'term_months', 'sub_grade',
       'verification_status', 'state_address'], dtype='<U19')

#### Sorting the dataset as per the smallest to largest IDs

In [371]:
min(loan_data[:,0]),max(loan_data[:,0])

(373332.0, 68616519.0)

In [372]:
loan_data=loan_data[np.argsort(loan_data[:,0])]

In [373]:
loan_data

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]])

In [374]:
np.argsort(loan_data[:,0])

array([   0,    1,    2, ..., 9997, 9998, 9999], dtype=int64)

#### Storing the new dataset 

In [376]:
loan_data=np.vstack((header_full,loan_data))
#stacking the column headers at top

In [378]:
#saving the dataset as a csv file
np.savetxt("loan-data-preprocessed.csv",loan_data,
           fmt="%s",
          delimiter=',')